#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'Ubuntu (RTX 3080 Passthrough Only)' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-e6ee5cd4-6c5c-4e35-a46e-23ee27cb91ba' {
        recordfail
        load_video
        gfxmode $linux_gfx_mode
        insmod gzio
        if [ x$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
        insmod part_gpt
        insmod ext2
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root  e6ee5cd4-6c5c-4e35-a46e-23ee27cb91ba
        else
          search --no-floppy --fs-uuid --set=root e6ee5cd4-6c5c-4e35-a46e-23ee27cb91ba
        fi
        linux   /boot/vmlinuz-5.11.0-25-generic root=UUID=e6ee5cd4-6c5c-4e35-a46e-23ee27cb91ba ro  quiet splash kvm.report_ignored_msrs=0 kvm.ignore_msrs=1 vfio-pci.ids=10de:2206,10de:1aef $vt_handoff
        initrd  /boot/initrd.img-5.11.0-25-generic
}